/*

 DIALOG_TILES_2BPP_GBCOMPRESSED.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char dialog_tiles[] =
{
  0xC5,0x00,0x00,0x0F,0x0F,0x10,0x10,0x09,
  0x20,0xC3,0x00,0x00,0xFF,0xFF,0x0D,0x00,
  0xC3,0xF8,0xF8,0x0C,0x0C,0x19,0x06,0x0F,
  0x20,0x00
};

/* End of DIALOG_TILES_2BPP_GBCOMPRESSED.C */
