/*

 DIALOG_TILES_2BPP_GBCOMPRESSED.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __dialog_tiles_2bpp_gbcompressed_h_INCLUDE
#define __dialog_tiles_2bpp_gbcompressed_h_INCLUDE

/* Bank of tiles. */
#define dialog_tilesBank 0
/* Start of tile array. */
extern const unsigned char dialog_tiles[];

#endif

/* End of DIALOG_TILES_2BPP_GBCOMPRESSED.H */
