/*

 FONT_NUM_TILES_1BPP_GBCOMPRESSED.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __font_num_tiles_1bpp_gbcompressed_h_INCLUDE
#define __font_num_tiles_1bpp_gbcompressed_h_INCLUDE

/* Bank of tiles. */
#define font_num_tilesBank 0

/* Super Gameboy palette 0 */
#define font_num_tilesSGBPal0c0 12556
#define font_num_tilesSGBPal0c1 10948
#define font_num_tilesSGBPal0c2 24576
#define font_num_tilesSGBPal0c3 47

/* Super Gameboy palette 1 */
#define font_num_tilesSGBPal1c0 6076
#define font_num_tilesSGBPal1c1 8935
#define font_num_tilesSGBPal1c2 6596
#define font_num_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define font_num_tilesSGBPal2c0 6076
#define font_num_tilesSGBPal2c1 8935
#define font_num_tilesSGBPal2c2 6596
#define font_num_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define font_num_tilesSGBPal3c0 6076
#define font_num_tilesSGBPal3c1 8935
#define font_num_tilesSGBPal3c2 6596
#define font_num_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define font_num_tilesCGBPal0c0 32767
#define font_num_tilesCGBPal0c1 21140
#define font_num_tilesCGBPal0c2 9513
#define font_num_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define font_num_tilesCGBPal1c0 6076
#define font_num_tilesCGBPal1c1 8935
#define font_num_tilesCGBPal1c2 6596
#define font_num_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define font_num_tilesCGBPal2c0 6076
#define font_num_tilesCGBPal2c1 8935
#define font_num_tilesCGBPal2c2 6596
#define font_num_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define font_num_tilesCGBPal3c0 6076
#define font_num_tilesCGBPal3c1 8935
#define font_num_tilesCGBPal3c2 6596
#define font_num_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define font_num_tilesCGBPal4c0 6076
#define font_num_tilesCGBPal4c1 8935
#define font_num_tilesCGBPal4c2 6596
#define font_num_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define font_num_tilesCGBPal5c0 6076
#define font_num_tilesCGBPal5c1 8935
#define font_num_tilesCGBPal5c2 6596
#define font_num_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define font_num_tilesCGBPal6c0 6076
#define font_num_tilesCGBPal6c1 8935
#define font_num_tilesCGBPal6c2 6596
#define font_num_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define font_num_tilesCGBPal7c0 6076
#define font_num_tilesCGBPal7c1 8935
#define font_num_tilesCGBPal7c2 6596
#define font_num_tilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char font_num_tiles[];

#endif

/* End of FONT_NUM_TILES_1BPP_GBCOMPRESSED.H */
