/*

 INTRO_AND_DIALOG_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char intro_dialog_tiles[] =
{
  0xC2,0x00,0x0F,0x10,0x04,0x20,0xC1,0x00,
  0xFF,0x06,0x00,0xC1,0xF8,0x0C,0x04,0x06,
  0x07,0x20,0x0B,0x00,0xC3,0x10,0x00,0x00,
  0x00,0x07,0x06,0xC7,0x00,0x10,0x10,0x38,
  0xFE,0x38,0x10,0x10,0x00
};

/* End of INTRO_AND_DIALOG_TILES.C */
