//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sgb_border_data_H
#define METASPRITE_sgb_border_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sgb_border_data_TILE_ORIGIN 0
#define sgb_border_data_TILE_H 8
#define sgb_border_data_WIDTH 256
#define sgb_border_data_HEIGHT 224
#define sgb_border_data_TILE_COUNT 96
#define sgb_border_data_PALETTE_COUNT 4
#define sgb_border_data_MAP_ATTRIBUTES 0
#define sgb_border_data_TILE_PALS 0

BANKREF_EXTERN(sgb_border_data)

extern const palette_color_t sgb_border_data_palettes[16];
extern const uint8_t sgb_border_data_tiles[3072];

extern const unsigned char sgb_border_data_map[1792];

#endif