/*

		SFX_0C

		Sound Effect File.
		
		Info:
			Length			:	2
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_0C[] = {
192, // Header
2,
0, 34, 128, 240, 123, 135, 0, 34, 128, 128, 190, 135
};