/*

		SFX_10

		Sound Effect File.
		
		Info:
			Length			:	19
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_10_h_INCLUDE
#define __SFX_10_h_INCLUDE
#define CBTFX_PLAY_SFX_10 CBTFX_init(&SFX_10[0])
extern const unsigned char SFX_10[];
#endif