/*

		SFX_0D

		Sound Effect File.
		
		Info:
			Length			:	32
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_0D_h_INCLUDE
#define __SFX_0D_h_INCLUDE
#define CBTFX_PLAY_SFX_0D CBTFX_init(&SFX_0D[0])
extern const unsigned char SFX_0D[];
#endif