/*

		SFX_0B

		Sound Effect File.
		
		Info:
			Length			:	5
			Priority		:	8
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_0B[] = {
200, // Header
5,
0, 34, 128, 240, 89, 135, 0, 34, 128, 240, 214, 134, 0, 34, 128, 192, 178, 134, 0, 34, 128, 144, 114, 134, 0, 34, 128, 64, 66, 134
};