/*

		SFX_0A

		Sound Effect File.
		
		Info:
			Length			:	5
			Priority		:	1
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	const unsigned char SFX_0A[] = {
193, // Header
5,
0, 34, 128, 240, 237, 133, 0, 34, 128, 240, 39, 134, 0, 34, 128, 192, 114, 134, 0, 34, 128, 144, 178, 134, 0, 34, 128, 64, 57, 135
};