//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sgb_border_data_optimized_2_H
#define METASPRITE_sgb_border_data_optimized_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sgb_border_data_optimized_2_TILE_ORIGIN 0
#define sgb_border_data_optimized_2_TILE_H 8
#define sgb_border_data_optimized_2_WIDTH 256
#define sgb_border_data_optimized_2_HEIGHT 224
#define sgb_border_data_optimized_2_TILE_COUNT 83
#define sgb_border_data_optimized_2_PALETTE_COUNT 4
#define sgb_border_data_optimized_2_MAP_ATTRIBUTES 0
#define sgb_border_data_optimized_2_TILE_PALS 0

BANKREF_EXTERN(sgb_border_data_optimized_2)

extern const palette_color_t sgb_border_data_optimized_2_palettes[16];
extern const uint8_t sgb_border_data_optimized_2_tiles[2656];

extern const unsigned char sgb_border_data_optimized_2_map[1792];

#endif