/*

 LOGO_SPLASH_TILES_FERRANTE_TEXT_SKULLCAT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 40

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __logo_splash_tiles_ferrante_text_skullcat_h_INCLUDE
#define __logo_splash_tiles_ferrante_text_skullcat_h_INCLUDE

/* Bank of tiles. */
#define logo_splash_tilesBank 0

/* Super Gameboy palette 0 */
#define logo_splash_tilesSGBPal0c0 31340
#define logo_splash_tilesSGBPal0c1 10910
#define logo_splash_tilesSGBPal0c2 0
#define logo_splash_tilesSGBPal0c3 16291

/* Super Gameboy palette 1 */
#define logo_splash_tilesSGBPal1c0 6076
#define logo_splash_tilesSGBPal1c1 8935
#define logo_splash_tilesSGBPal1c2 6596
#define logo_splash_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define logo_splash_tilesSGBPal2c0 6076
#define logo_splash_tilesSGBPal2c1 8935
#define logo_splash_tilesSGBPal2c2 6596
#define logo_splash_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define logo_splash_tilesSGBPal3c0 6076
#define logo_splash_tilesSGBPal3c1 8935
#define logo_splash_tilesSGBPal3c2 6596
#define logo_splash_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define logo_splash_tilesCGBPal0c0 32767
#define logo_splash_tilesCGBPal0c1 21140
#define logo_splash_tilesCGBPal0c2 9513
#define logo_splash_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define logo_splash_tilesCGBPal1c0 6076
#define logo_splash_tilesCGBPal1c1 8935
#define logo_splash_tilesCGBPal1c2 6596
#define logo_splash_tilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define logo_splash_tilesCGBPal2c0 6076
#define logo_splash_tilesCGBPal2c1 8935
#define logo_splash_tilesCGBPal2c2 6596
#define logo_splash_tilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define logo_splash_tilesCGBPal3c0 6076
#define logo_splash_tilesCGBPal3c1 8935
#define logo_splash_tilesCGBPal3c2 6596
#define logo_splash_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define logo_splash_tilesCGBPal4c0 6076
#define logo_splash_tilesCGBPal4c1 8935
#define logo_splash_tilesCGBPal4c2 6596
#define logo_splash_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define logo_splash_tilesCGBPal5c0 6076
#define logo_splash_tilesCGBPal5c1 8935
#define logo_splash_tilesCGBPal5c2 6596
#define logo_splash_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define logo_splash_tilesCGBPal6c0 6076
#define logo_splash_tilesCGBPal6c1 8935
#define logo_splash_tilesCGBPal6c2 6596
#define logo_splash_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define logo_splash_tilesCGBPal7c0 6076
#define logo_splash_tilesCGBPal7c1 8935
#define logo_splash_tilesCGBPal7c2 6596
#define logo_splash_tilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char logo_splash_tiles[];

#endif

/* End of LOGO_SPLASH_TILES_FERRANTE_TEXT_SKULLCAT.H */
