/*

 LOGO_SPLASH_MAP_FERRANTE_TEXT_SKULLCAT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 6
   Tile set      : logo_splash_ferrante_text_skullcat.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __logo_splash_map_ferrante_text_skullcat_h_INCLUDE
#define __logo_splash_map_ferrante_text_skullcat_h_INCLUDE

#define logo_splash_mapWidth 16
#define logo_splash_mapHeight 6
#define logo_splash_mapBank 0

#define logo_splash_map logo_splash_mapPLN0
extern const unsigned char logo_splash_mapPLN0[];

#endif

/* End of LOGO_SPLASH_MAP_FERRANTE_TEXT_SKULLCAT.H */
